[toc]

---

[出处](http://www.imooc.com/article/263959)

# 执行协程
协程（coroutines）是通过async/await定义函数或方法，是使用asyncio进行异步编程的首选途径。如下，是一个协程的例子：
```py
import asyncio

async def main():   # async: 定义协程
    print("hello")
    await asyncio.sleep(1)
    print("world")
```
上例中的 main 方法就是我们定义的协程 。
我们在交互环境(Python3.7)下执行以上代码，看看效果：
```py
>>> import asyncio
>>> async def main():
...     print("hello")
...     await asyncio.sleep(1)
...     print("world")


>>> asyncio.run(main())     # run: 运行协程
hello
world
```
需要注意的是：
如果像执行普通代码一样直接调用`main()`，只会返回一个coroutine对象，`main()`方法内的代码不会执行：
```py
>>> main()      # 直接执行 main() 返回的是一个 coroutine 对象。
<coroutine object main at 0x0000000002C97848>
```
<br>

实际上，`asyncio` 提供了三种执行协程的机制：
## 1. run()（执行
使用`asyncio.run()`执行协程。
一般用于<u>执行最顶层的入口函数</u>，如`main()`。
<br>

## 2. await（等待
`await`一个协程。
一般用于<u>在一个协程中调用另一协程</u>。 如下是一个示例：

```py
>>> import time
>>> async def say_after(delay, word):
        await asyncio.sleep(delay)
        print(word)

>>> async def main():
        print(f"started at {time.strftime('%X')}")
        await say_after(1, "hello")  # await: 在一个协程中调用另一协程
        await say_after(2, "world")
        print(f"finished at {time.strftime('%X')}")


>>> asyncio.run(main())
started at 16:47:10
hello
world
finished at 16:47:13
# 执行耗时 3秒
```

##3. create_task()（创建任务
用`asyncio.create_task()`方法将 Coroutine（协程）<u>封装为 Task（任务）</u>。
一般用于实现异步并发操作。 <br>
注意：
<u>只有在当前线程存在 ==**事件循环**== 的时候才能创建任务（Task）</u>。<br>
我们修改以上的例程，**并发** 执行 两个say_after协程。

```py
async def main():
    task1 = asyncio.create_task(say_after(1, "hello"))
    task2 = asyncio.create_task(say_after(2, "world"))
    print(f"started at {time.strftime('%X')}")
    await task1
    await task2
    print(f"finished at {time.strftime('%X')}")


asyncio.run(main())
```
结果：
```py
started at 17:01:34
hello
world
finished at 17:01:36
# 耗时2秒
```

<br>

# “可等待”对象（Awaitables object）
如果一个对象能够被用在 await 表达式中，那么我们称这个对象是可等待对象。
很多asyncio API都被设计成了可等待的。

主要有三类可等待对象：
- 协程 `coroutine`
- 任务 `Task`
- 未来对象 `Future` 。


## coroutine（协程 
Python 的协程是可等待的 (awaitable)，因此能够被其他协程用在 await 表达式中。
```py
import asyncio


async def nested():     # 协程函数
    print("something")


async def main():
    # 直接调用的时候只是创建了一个 协程对象 ，但这个对象没有被 await, 所以它并不会执行.
    nested()        # 什么都不会发生. 只声明一个协程对象
    await nested()  # 打印 "something".


asyncio.run(main())
```
在这篇文章中，术语 `coroutine` 或协程指代两个关系紧密的概念：
- ==**协程函数** coroutine function ：由 `async def` 定义的函数==；
- **协程对象** coroutine object ：调用 协程函数返回的对象。

<br>

## Task（任务
Task ： 用来 ==并发== 的**调度协程**。
<u>
当一个协程通过类似 asyncio.`create_task()` 的函数被封装进一个 Task 时，这个协程 会很快被 **自动** 调度执行：</u>

```py
import asyncio


async def nested():
    return 42


async def main():
    task = asyncio.create_task(nested())# Schedule nested() to run soon concurrently with "main()".
    await task                          # "task" can now be used to cancel "nested()", or can simply be awaited to wait until it is complete:


asyncio.run(main())
```
<br>

## Future（未来对象
Future 是一种特殊的 底层 可等待对象，代表 **一个异步操作的最终结果**。
当一个Future对象被await的时候，表示当前的协程会持续等待，直到 Future对象所指向的异步操作执行完毕。

- 在asyncio中，Future对象能使 **基于回调** 的代码被用于asyn/await表达式中。
- 一般情况下，在应用层编程中，没有必要 创建Future对象。
<br>

有时候，有些 Future 对象会被一些库和 asyncio API 暴露出来，我们可以 await 它们：
```py
async def main():
    await function_that_returns_a_future_object()

    # this is also valid:
    await asyncio.gather(
        function_that_returns_a_future_object(),
        some_python_coroutine()
    )
```
底层函数返回Future对象的一个例子是：[loop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor)

<br>

# 执行 asyncio 程序
这个函数作用：
- 运行 `coro` 指定的 协程，
- 负责 管理 asyncio 事件循环，
- 终止异步生成器。 
```py
asyncio.run(coro, * , debug=False)
```
- 在同一个线程中，当已经有 asyncio 事件循环在执行时，不能调用此函数。 
- 如果 `debug=True` ，事件循环将运行在 **调试模式**。
- 此函数总是创建一个<u>新的事件循环</u>，并在最后关闭它。

建议将它用作 asyncio 程序的主入口，并且只调用一次。 
重要：这个函数是在 Python3.7 被临时添加到 asyncio 中的。

<br>

# 创建 Task
将 `coro` 指定的协程（coroutine）==**封装**== 到一个Task中，并 **调度** 执行。
返回值是一个 Task 对象。
```py
asyncio.create_task(coro)
```

任务在由 `get_running_loop()` 返回的事件循环（loop）中执行。
如果当前线程中没有正在运行的事件循环，将会引发 **RuntimeError 异常**:

```py
import asyncio

async def coro_1():
    print("do somthing")

task = asyncio.create_task(coro_1())
```
因为当前线程中没有正运行的事件循环，所以引发异常：

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-456c15a4ed16>", line 1, in <module>
    task = asyncio.create_task(coro_1())
  File "C:\Program Files\Python37\lib\asyncio\tasks.py", line 324, in create_task
    loop = events.get_running_loop()
RuntimeError: no running event loop
```
对以上代码稍作修改，创建main()方法，在其中创建Task对象，然后在主程序中利用asyncio.run()创建事件循环：

```py
import asyncio

async def coro():
    print("something is running")

async def main():
    task = asyncio.create_task(coro())
    print(asyncio.get_running_loop())
    
asyncio.run(main())
```
执行结果如下：

```
<_WindowsSelectorEventLoop running=True closed=False debug=False>
something is running
```
此函数已经被引入到Python3.7。
在Python早期版本中，可以使用底层函数 `asyncio.ensure_future()` 代替。

```py
async def coro():
    ...
# In Python 3.7+
task = asyncio.create_task(coro())
...
# This works in all Python versions but is less readable
task = asyncio.ensure_future(coro())
...
```

下面的暂时不看 现在没用过，只能看懂基本的（其实基本的都一头雾水了）。等用过了再继续看这个






<br><br><br><br>
<br><br><br><br><br>

```py

```
```py

```
```py

```
```py

```
```py

```
```py

```
```py

```
```py

```
```py

```
```py

```
```py

```












